// services/huggingFaceService.js

const ApiError = require('../utils/ApiError');

const HF_TOKEN = process.env.HF_TOKEN;
const HF_API_BASE_URL = process.env.HF_API_BASE_URL || 'https://router.huggingface.co/v1';
const model = process.env.LLM_MODEL;

console.log(`[HF Service] Loaded model: ${model}`);
console.log(`[HF Service] Token prefix: ${HF_TOKEN?.substring(0, 10)}...`);

if (!HF_TOKEN || !model) {
    throw new Error("Missing required environment variables: HF_TOKEN and LLM_MODEL must be set.");
}

/**
 * Invokes the Hugging Face Router API using OpenAI-compatible endpoint.
 * @param {string} prompt - The complete prompt to send to the LLM.
 * @param {string} taskDescription - A short description of the task for logging/error purposes.
 * @returns {Promise<string>} The text generated by the model.
 * @throws {ApiError} If the API call fails or returns an empty response.
 */
const invokeModel = async (prompt, taskDescription) => {
    console.log(`--- Invoking LLM for: ${taskDescription} ---`);
    console.log(`[HF Service] Using REAL API with token: ${HF_TOKEN?.substring(0, 15)}...`);
    console.log(`[HF Service] Model: ${model}`);
    console.log(`[HF Service] API Base URL: ${HF_API_BASE_URL}`);

    // Always use real API - never use mock mode
    const useMockMode = false;

    if (useMockMode) {
        console.log(`--- Using MOCK response for: ${taskDescription} ---`);

        // Extract topic from prompt dynamically
        const topicMatch = prompt.match(/understanding of "([^"]+)"/i) ||
            prompt.match(/about "([^"]+)"/i) ||
            prompt.match(/topic of "([^"]+)"/i);
        const topic = topicMatch ? topicMatch[1] : 'the topic';

        const mockResponses = {
            'quiz generation': JSON.stringify({
                questions: [
                    { id: 1, question: `What are the fundamental concepts and core principles of ${topic}?` },
                    { id: 2, question: `How would you apply ${topic} to a real-world scenario or problem?` },
                    { id: 3, question: `What are some advanced or nuanced aspects of ${topic} that require critical thinking?` }
                ]
            }),
            'learner analysis': (() => {
                // Extract answers from prompt
                const answersMatch = prompt.match(/Answer: ([^\n]+)/gi) || [];
                const answers = answersMatch.map(a => a.replace('Answer: ', '').trim());

                // Calculate average answer length (longer = more detailed)
                const avgLength = answers.reduce((sum, ans) => sum + ans.length, 0) / Math.max(answers.length, 1);

                // Count quality indicators
                let qualityScore = 0;
                const fullText = answers.join(' ').toLowerCase();

                // Check for depth indicators
                if (fullText.includes('example')) qualityScore += 15;
                if (fullText.includes('for instance') || fullText.includes('such as')) qualityScore += 15;
                if (fullText.includes('however') || fullText.includes('although')) qualityScore += 10;
                if (fullText.includes('because') || fullText.includes('reason')) qualityScore += 10;
                if (fullText.includes('complex') || fullText.includes('advanced')) qualityScore += 10;
                if (fullText.includes('system') || fullText.includes('framework')) qualityScore += 10;
                if (avgLength > 100) qualityScore += Math.min((avgLength - 100) / 20, 15);
                if (avgLength > 200) qualityScore += 10;

                // Base score + quality
                let score = 50 + qualityScore;
                score = Math.min(Math.round(score), 95); // Cap at 95

                // Determine strengths and weaknesses
                const strengths = [];
                const weaknesses = [];

                if (fullText.includes('example') || fullText.includes('like')) {
                    strengths.push(`practical examples in ${topic}`);
                } else {
                    weaknesses.push(`providing clear examples in ${topic}`);
                }

                if (fullText.includes('concept') || fullText.includes('theory') || fullText.includes('principle')) {
                    strengths.push(`conceptual understanding of ${topic}`);
                } else {
                    weaknesses.push(`theoretical depth in ${topic}`);
                }

                if (fullText.includes('use') || fullText.includes('apply') || fullText.includes('implement')) {
                    strengths.push(`practical application of ${topic}`);
                } else {
                    weaknesses.push(`real-world application of ${topic}`);
                }

                if (answers.some(a => a.length < 20)) {
                    weaknesses.push(`detailed explanations in ${topic}`);
                }

                if (strengths.length === 0) strengths.push(`foundational knowledge of ${topic}`);
                if (weaknesses.length === 0) weaknesses.push(`some advanced concepts in ${topic}`);

                const performanceLevel = score >= 80 ? 'excellent' : score >= 60 ? 'solid' : score >= 40 ? 'developing' : 'needs improvement';
                const summary = `Your understanding of ${topic} shows ${performanceLevel} comprehension at ${score}%. Focus on deepening your ${weaknesses[0]}.`;

                return JSON.stringify({
                    score: score,
                    weak_topics: weaknesses.slice(0, 2),
                    strengths: strengths.slice(0, 2),
                    summary: summary
                });
            })(),
            'beginner explanation': `Let's strengthen your understanding of ${topic}. Key areas to focus on:\n\n1. **Core Concepts**: Review the fundamental principles that ${topic} is built on. Ask yourself: "What are the absolute basics?"\n\n2. **Foundational Examples**: Study simple, clear examples of ${topic} in action. Understanding through examples is crucial.\n\n3. **Building Blocks**: ${topic} has interconnected concepts. Make sure you understand how different parts relate.\n\n4. **Practice**: Apply what you learn through simple exercises before moving to complex problems.\n\nRemember: mastery takes time. Start with fundamentals and gradually build complexity!`,
            'advanced challenge': `You've shown good understanding of ${topic}. Ready for a challenge?\n\n**Level 1 Challenge**: Take two concepts from ${topic} and explain how they work together in a real system.\n\n**Level 2 Challenge**: Design a solution to a real-world problem using advanced aspects of ${topic}.\n\n**Level 3 Challenge**: Optimize your solution by considering performance, scalability, and edge cases.\n\nChoose the level that excites you and push your boundaries!`,
            'learning roadmap': (() => {
                // Generate dynamic roadmap based on score from prompt
                const scoreMatch = prompt.match(/adjusted_score["\s:]*(\d+)/i) || prompt.match(/score["\s:]*(\d+)/i);
                const score = scoreMatch ? parseInt(scoreMatch[1]) : 50;

                if (score >= 80) {
                    return `🚀 You're Advanced! Focus on Mastery:\nDay 1-2: Explore cutting-edge applications and research in ${topic}\nDay 3-4: Contribute to open-source projects using ${topic}\nDay 5-6: Teach others or write about advanced concepts in ${topic}\nDay 7: Build a complex, production-ready solution using ${topic}`;
                } else if (score >= 60) {
                    return `📈 Good Foundation - Build on Your Strengths:\nDay 1-2: Deepen understanding of intermediate concepts in ${topic}\nDay 3-4: Study real-world case studies of ${topic}\nDay 5-6: Implement ${topic} in small projects\nDay 7: Integrate ${topic} into a larger application`;
                } else {
                    return `📚 Build Your Foundation:\nDay 1-2: Master fundamental concepts and definitions of ${topic}\nDay 3-4: Study simple examples and use cases for ${topic}\nDay 5-6: Practice implementing basic ${topic} concepts\nDay 7: Review weak areas and plan next steps for ${topic}`;
                }
            })(),
            'judge: quiz quality': JSON.stringify({
                difficulty_level: 'medium',
                is_well_formed: true,
                confidence: 0.88,
                feedback: `Well-constructed questions about ${topic} that test understanding at multiple levels. Good progression from basic to advanced.`
            }),
            'judge: analysis validation': JSON.stringify({
                adjusted_score: 70,
                confidence_level: 0.85,
                validates_initial_analysis: true,
                suggested_adjustments: [`Student shows promise in ${topic}`, 'Focus on practical application for growth'],
                judge_notes: `Analysis is accurate. Student understanding of ${topic} is solid but needs more practice with applications.`
            })
        };
        return mockResponses[taskDescription] || 'Mock response for: ' + taskDescription;
    }

    try {
        console.log(`[HF Service] Sending request to: ${HF_API_BASE_URL}/chat/completions`);
        const response = await fetch(`${HF_API_BASE_URL}/chat/completions`, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${HF_TOKEN}`,
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                model: model,
                messages: [
                    {
                        role: 'user',
                        content: prompt,
                    },
                ],
                max_tokens: 1024,
                temperature: 0.7,
            }),
            timeout: 60000,
        });

        console.log(`[HF Service] Response status: ${response.status} ${response.statusText}`);

        if (!response.ok) {
            const errorText = await response.text();
            console.error(`[ERROR] HuggingFace API returned ${response.status}:`, errorText);
            throw new ApiError(`HuggingFace API Error: ${response.status} ${response.statusText}. ${errorText}`, response.status);
        }

        const data = await response.json();
        console.log(`[HF Service] Response received:`, JSON.stringify(data).substring(0, 200));

        const generatedText = data.choices?.[0]?.message?.content;

        if (!generatedText || generatedText.trim() === '') {
            throw new ApiError(`LLM failed to generate a response for ${taskDescription}.`, 502);
        }

        console.log(`--- LLM invocation successful for: ${taskDescription} ---`);
        return generatedText;

    } catch (error) {
        console.error(`[CRITICAL ERROR] HuggingFace API failed during ${taskDescription}:`, error.message);
        console.error(`[ERROR DETAILS]`, error);
        throw error;
    }
}

/**
 * Generates intelligent mock responses that analyze answers for CORRECTNESS
 */
const generateIntelligentMockResponse = (prompt, taskDescription) => {
    console.log(`--- Using INTELLIGENT MOCK response for: ${taskDescription} ---`);

    // Extract topic
    const topicMatch = prompt.match(/understanding of "([^"]+)"/i) ||
        prompt.match(/about "([^"]+)"/i) ||
        prompt.match(/topic of "([^"]+)"/i);
    const topic = topicMatch ? topicMatch[1] : 'the topic';

    if (taskDescription === 'quiz generation') {
        return JSON.stringify({
            questions: [
                { id: 1, question: `What are the fundamental concepts and core principles of ${topic}?` },
                { id: 2, question: `How would you apply ${topic} to a real-world scenario or problem?` },
                { id: 3, question: `What are some advanced or nuanced aspects of ${topic} that require critical thinking?` }
            ]
        });
    }

    if (taskDescription === 'learner analysis') {
        // Extract answers and analyze correctness
        const answersMatch = prompt.match(/Answer: ([^\n]+)/gi) || [];
        const answers = answersMatch.map(a => a.replace('Answer: ', '').trim());

        // Analyze answer quality for CORRECTNESS
        let correctnessScore = 0;
        const fullText = answers.join(' ').toLowerCase();

        // Check for conceptual correctness indicators
        if (fullText.length > 150) correctnessScore += 20;
        if (fullText.includes('concept') || fullText.includes('principle') || fullText.includes('definition')) correctnessScore += 15;
        if (fullText.includes('example') || fullText.includes('instance') || fullText.includes('like')) correctnessScore += 15;
        if (fullText.includes('reason') || fullText.includes('because') || fullText.includes('why')) correctnessScore += 10;
        if (fullText.includes('system') || fullText.includes('framework') || fullText.includes('structure')) correctnessScore += 10;
        if (fullText.includes('implement') || fullText.includes('apply') || fullText.includes('use')) correctnessScore += 10;
        if (fullText.includes('complex') || fullText.includes('advanced') || fullText.includes('sophisticated')) correctnessScore += 10;
        if (answers.every(a => a.length > 20)) correctnessScore += 10;

        const score = Math.min(50 + correctnessScore, 95);

        // Determine feedback based on CORRECTNESS level
        const strengths = [];
        const weaknesses = [];

        if (fullText.includes('concept') || fullText.includes('principle')) {
            strengths.push(`understanding core concepts of ${topic}`);
        } else {
            weaknesses.push(`explaining core concepts of ${topic}`);
        }

        if (fullText.includes('example') || fullText.includes('instance')) {
            strengths.push(`providing examples in ${topic}`);
        } else {
            weaknesses.push(`providing concrete examples in ${topic}`);
        }

        if (fullText.includes('apply') || fullText.includes('use') || fullText.includes('implement')) {
            strengths.push(`applying ${topic} practically`);
        } else {
            weaknesses.push(`applying ${topic} to real problems`);
        }

        if (strengths.length === 0) strengths.push(`foundational knowledge of ${topic}`);
        if (weaknesses.length === 0) weaknesses.push(`advanced aspects of ${topic}`);

        const performanceLevel = score >= 80 ? 'excellent' : score >= 60 ? 'solid' : score >= 40 ? 'developing' : 'needs improvement';
        const summary = `Your answers show ${performanceLevel} understanding of ${topic} at ${score}%. Your strongest area: ${strengths[0]}. Focus on: ${weaknesses[0]}.`;

        return JSON.stringify({
            score: score,
            weak_topics: weaknesses.slice(0, 2),
            strengths: strengths.slice(0, 2),
            summary: summary
        });
    }

    if (taskDescription === 'beginner explanation') {
        return `Let's strengthen your understanding of ${topic}. Here are key areas to focus on:\n\n1. **Definitions**: Make sure you understand what ${topic} fundamentally means\n\n2. **Core Concepts**: Learn the basic building blocks of ${topic}\n\n3. **Simple Examples**: Study easy-to-understand examples of ${topic} in action\n\n4. **Connections**: Understand how different parts of ${topic} relate to each other\n\nStart with fundamentals and gradually build complexity!`;
    }

    if (taskDescription === 'advanced challenge') {
        return `You've shown good understanding of ${topic}. Ready for a challenge?\n\n**Challenge 1**: Combine two concepts from ${topic} and explain their interaction\n\n**Challenge 2**: Design a solution to a real-world problem using ${topic}\n\n**Challenge 3**: Optimize your solution considering edge cases and performance\n\nChoose the level that excites you!`;
    }

    if (taskDescription === 'learning roadmap') {
        const scoreMatch = prompt.match(/score["\s:]*(\d+)/i) || prompt.match(/adjusted_score["\s:]*(\d+)/i);
        const score = scoreMatch ? parseInt(scoreMatch[1]) : 50;

        if (score >= 80) {
            return `🚀 Practical 7-Day Roadmap for ${topic} (Advanced learner):
Day 1: Review advanced architecture and design patterns for ${topic}. Read one case study or technical blog and summarize key takeaways.
Day 2: Build a focused component or module using ${topic} that demonstrates performance, scalability, or advanced features.
Day 3: Explore real-world applications and identify common production challenges. Document how ${topic} is used in practice.
Day 4: Improve the component by adding tests, edge-case handling, or performance profiling.
Day 5: Create a short technical write-up or presentation explaining the design decisions.
Day 6: Compare two approaches related to ${topic} and summarize when to use each.
Day 7: Plan a follow-up project that combines ${topic} with a complementary technology and outline next learning milestones.

Common job roles that use ${topic}:
- Software Engineer
- Full-Stack Developer
- DevOps Engineer
- Technical Consultant

What to do next: continue with a larger project, contribute to open source, and deepen the skills you practiced this week.`;
        } else if (score >= 60) {
            return `📈 Practical 7-Day Roadmap for ${topic} (Intermediate learner):
Day 1: Review core concepts and terminology for ${topic}. Read a tutorial or official docs and capture the main ideas.
Day 2: Follow a guided example to build a hands-on sample that uses ${topic} in a real context.
Day 3: Practice the weakest two areas from your assessment with short exercises.
Day 4: Build a slightly larger example that combines ${topic} with related tools or concepts.
Day 5: Test your example, fix issues, and iterate on the design.
Day 6: Study one real-world case study or blog post and compare it with your own work.
Day 7: Summarize the week, identify gaps, and create a 2-week follow-up plan.

Common job roles that use ${topic}:
- Junior Software Developer
- QA Engineer
- Integration Specialist
- Technical Support Engineer

What to do next: continue practicing through a small project and apply the concepts in a real scenario.`;
        } else {
            return `📚 Practical 7-Day Roadmap for ${topic} (Beginner learner):
Day 1: Learn the basic definitions and foundational ideas of ${topic}. Use one introductory tutorial and take notes.
Day 2: Study simple examples and follow a guided walkthrough showing ${topic} in practice.
Day 3: Practice the fundamentals with short exercises focused on the building blocks.
Day 4: Apply those basics to a small toy problem or simple project.
Day 5: Review the weak topics from your assessment and repeat the most important exercises.
Day 6: Compare two examples or implementations and explain the differences in your own words.
Day 7: Create a summary of what you learned, list remaining questions, and make a longer learning plan.

Common job roles that use ${topic}:
- Entry-Level Developer
- Support Engineer
- Intern / Trainee
- Junior Technical Analyst

What to do next: keep learning with structured courses, hands-on projects, and by practicing the concepts you found hardest.`;
        }
    }

    return 'Mock response for: ' + taskDescription;
};

module.exports = {
    invokeModel,
};
