// services/huggingFaceService.js

const ApiError = require('../utils/ApiError');

const HF_TOKEN = process.env.HF_TOKEN;
const HF_API_BASE_URL = process.env.HF_API_BASE_URL || 'https://router.huggingface.co/v1';
const model = process.env.LLM_MODEL;

if (!HF_TOKEN || !model) {
    throw new Error("Missing required environment variables: HF_TOKEN and LLM_MODEL must be set.");
}

/**
 * Invokes the Hugging Face Router API using OpenAI-compatible endpoint.
 * @param {string} prompt - The complete prompt to send to the LLM.
 * @param {string} taskDescription - A short description of the task for logging/error purposes.
 * @returns {Promise<string>} The text generated by the model.
 * @throws {ApiError} If the API call fails or returns an empty response.
 */
const invokeModel = async (prompt, taskDescription) => {
    console.log(`--- Invoking LLM for: ${taskDescription} ---`);

    // MOCK MODE: Return mock responses for testing
    const useMockMode = process.env.NODE_ENV === 'development' && !HF_TOKEN.includes('hf_');

    if (useMockMode) {
        console.log(`--- Using MOCK response for: ${taskDescription} ---`);
        const mockResponses = {
            'quiz generation': JSON.stringify({
                questions: [
                    { id: 1, question: 'What are the fundamental concepts and core principles of this topic?' },
                    { id: 2, question: 'How would you apply this topic to a real-world scenario or problem?' },
                    { id: 3, question: 'What are some advanced or nuanced aspects of this topic that require critical thinking?' }
                ]
            }),
            'learner analysis': JSON.stringify({
                score: 72,
                weak_topics: ['variable scope', 'async/await'],
                strengths: ['basic syntax', 'data types'],
                summary: 'You have a solid understanding of the basics but need practice with advanced concepts.'
            }),
            'beginner explanation': 'Variable scope in Python refers to where a variable is accessible in your code. Think of it like a box: variables inside the box can only be seen inside that box. This helps organize code and prevent naming conflicts.',
            'advanced challenge': 'Create a Promise-based rate limiter that allows maximum 3 API calls per second. Your solution should queue excess requests.',
            'learning roadmap': 'Day 1-2: Review variable scope basics\nDay 3-4: Practice with closure exercises\nDay 5-6: Implement async/await examples\nDay 7: Build a project combining both concepts',
            'judge: quiz quality': JSON.stringify({
                difficulty_level: 'medium',
                is_well_formed: true,
                confidence: 0.92,
                feedback: 'Well-structured questions that progress logically from foundational to advanced concepts. Questions are clear and unambiguous.'
            }),
            'judge: analysis validation': JSON.stringify({
                adjusted_score: 75,
                confidence_level: 0.88,
                validates_initial_analysis: true,
                suggested_adjustments: ['Consider the depth of answer for Q2', 'Strong conceptual understanding evident'],
                judge_notes: 'Initial analysis is sound. Score adjusted slightly upward due to quality of explanations provided.'
            })
        };
        return mockResponses[taskDescription] || 'Mock response for: ' + taskDescription;
    }

    try {
        const response = await fetch(`${HF_API_BASE_URL}/chat/completions`, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${HF_TOKEN}`,
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                model: model,
                messages: [
                    {
                        role: 'user',
                        content: prompt,
                    },
                ],
                max_tokens: 1024,
                temperature: 0.7,
            }),
        });

        if (!response.ok) {
            const errorData = await response.json();
            console.error(`API Error Response:`, errorData);
            throw new Error(`HTTP ${response.status}: ${errorData.error?.message || 'Unknown error'}`);
        }

        const data = await response.json();
        const generatedText = data.choices?.[0]?.message?.content;

        if (!generatedText || generatedText.trim() === '') {
            throw new ApiError(`LLM failed to generate a response for ${taskDescription}.`, 502);
        }

        console.log(`--- LLM invocation successful for: ${taskDescription} ---`);
        return generatedText;

    } catch (error) {
        console.error(`HuggingFace Router API Error during ${taskDescription}:`, error.message);
        throw new ApiError(`Failed to get a response from the AI model for ${taskDescription}. Error: ${error.message}`, 503);
    }
};

module.exports = {
    invokeModel,
};
